name: Node CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js current LTS
      uses: actions/setup-node@v1
      with:
        node-version: 'lts/*'
    - name: yarn install and test
      run: |
        yarn install
        yarn test
      env:
        CI: true
